# Generated by Django 4.0.5 on 2022-08-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=100)),
                ('emp_dest', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('emp_dept', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
