# Generated by Django 4.0.5 on 2022-08-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_rec_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empprofile',
            name='emp_code',
        ),
    ]
