# Generated by Django 4.0.5 on 2022-08-07 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emp_rec_management', '0002_remove_empprofile_emp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_dept', models.CharField(max_length=100, null=True)),
                ('emp_desig', models.CharField(max_length=100, null=True)),
                ('contact_no', models.CharField(max_length=15, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='empProfile',
        ),
    ]
