# Generated by Django 4.0.5 on 2022-08-07 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emp_rec_management', '0003_emp_details_delete_empprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp_Details',
            new_name='EmployeeDetails',
        ),
    ]
