# Generated by Django 4.0.5 on 2022-08-09 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emp_rec_management', '0006_remove_employeedetails_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='email',
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='contact_no',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
