# Generated by Django 3.2.10 on 2022-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_rec_management', '0008_alter_employeedetails_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='emp_dept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='emp_desig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
